apiVersion: v1
kind: Service
metadata:
  name: {{ include "smi-metrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "smi-metrics.name" . }}
    helm.sh/chart: {{ include "smi-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: api
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "smi-metrics.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
