version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Dependencies
          command: |
            make dep
      - run:
          name: Running unit tests
          command: |
            make lint test
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker build and push
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              make push

  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/deislabs/smi-metrics
    steps:
      - checkout
      - run:
          name: Checking if the commit is a release
          command: |
            make release

workflows:
  version: 2
  test-build-publish:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        requires:
        - test
        filters:
          tags:
            only: /.*/
          branches:
            only: master
    - release:
        requires:
        - build
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
