name: Build and Testing
on:
  pull_request: {}
  push:
    tags:
      - 'v*.*.*'
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - master
jobs:
  go_build_test:
    name: Go Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Validate go deps
      run: |
        make dep
    - name: Running go linting and unit tests
      run: |
         make lint test
  docker_build:
    name: Docker Build
    needs: go_build_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        make build
  release:
    name: Docker Push and Release
    needs: docker_build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'v')
    steps:
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Docker Build and Push
      run: |
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASS}}  && \
        make push
    - name: Performing a Github release
      run: |
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        make release
